"""add_feedback_system

Revision ID: 2d0b99aa1b4e
Revises: 20251231_123400
Create Date: 2026-01-06 17:35:27.745683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d0b99aa1b4e'
down_revision: Union[str, Sequence[str], None] = '20251231_123400'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import text
    
    print("Running feedback system migration...")
    
    # Check if has_given_feedback column exists before adding it
    connection = op.get_bind()
    result = connection.execute(text("""
        SELECT column_name 
        FROM information_schema.columns 
        WHERE table_name='users' AND column_name='has_given_feedback'
    """))
    
    if not result.fetchone():
        print("Adding has_given_feedback column to users table...")
        op.add_column('users', sa.Column('has_given_feedback', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        print("has_given_feedback column added successfully")
    else:
        print("ℹhas_given_feedback column already exists")
    
    # Check if user_feedback table exists before creating it
    result = connection.execute(text("""
        SELECT table_name 
        FROM information_schema.tables 
        WHERE table_name='user_feedback'
    """))
    
    if not result.fetchone():
        print("Creating user_feedback table...")
        op.create_table('user_feedback',
            sa.Column('id', sa.UUID(), nullable=False),
            sa.Column('user_id', sa.UUID(), nullable=False),
            sa.Column('rating', sa.Integer(), nullable=False),
            sa.Column('comment', sa.Text(), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id')
        )
        print("user_feedback table created successfully")
    else:
        print("ℹuser_feedback table already exists")
    
    print("Feedback system migration completed!")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import text
    
    connection = op.get_bind()
    
    # Drop user_feedback table if it exists
    result = connection.execute(text("""
        SELECT table_name 
        FROM information_schema.tables 
        WHERE table_name='user_feedback'
    """))
    
    if result.fetchone():
        op.drop_table('user_feedback')
    
    # Remove has_given_feedback column if it exists
    result = connection.execute(text("""
        SELECT column_name 
        FROM information_schema.columns 
        WHERE table_name='users' AND column_name='has_given_feedback'
    """))
    
    if result.fetchone():
        op.drop_column('users', 'has_given_feedback')
    # ### end Alembic commands ###
